export const queryKeys = {
  authMe: ['auth', 'me'] as const,
  dashboardSummary: ['dashboard', 'summary'] as const,
  patients: ['patients'] as const,
  patientTimeline: ['patients', 'timeline'] as const,
  appointments: ['appointments'] as const,
  services: ['services'] as const,
  drugs: ['drugs'] as const,
  prescriptions: ['prescriptions'] as const,
  staff: ['staff'] as const,
  doctors: ['staff', 'doctors'] as const,
  patientPortalDashboard: ['patient-portal', 'dashboard'] as const,
  patientPortalProfile: ['patient-portal', 'profile'] as const,
  patientPortalHistory: ['patient-portal', 'history'] as const,
  patientPortalVisitDetail: ['patient-portal', 'history', 'detail'] as const,
  patientPortalAppointments: ['patient-portal', 'appointments'] as const,
  patientPortalDoctors: ['patient-portal', 'doctors'] as const,
  patientPortalAvailableSlots: ['patient-portal', 'available-slots'] as const,
} as const
